version: "3.3"
services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: devops
    ports:
      - 3306:3306
    networks:
      - projectnetwork
    volumes:
      - db:/var/lib/mysql
  app-timesheet:
    depends_on:
      - mysqldb
    image: asma251/devops_project:2.1
    restart: on-failure
    ports:
      - 8089:8089
    networks:
      - projectnetwork
networks:
  projectnetwork:
volumes:
  db: